import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b4b5b5",
        "on-primary-fixed": "#4a0000",
        primary: "#ed0d11",
        outline: "#b18780",
        "on-error": "#690005",
        "on-tertiary-container": "#00285b",
        "on-surface-variant": "#ebbbb4",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#004491",
        "primary-container": "#b60b0e",
        "primary-fixed-dim": "#ff6a6d",
        "secondary-fixed": "#e2e2e2",
        "surface-bright": "#393939",
        "secondary-container": "#454747",
        background: "#131313",
        "inverse-surface": "#e2e2e2",
        surface: "#131313",
        "on-surface": "#e2e2e2",
        "on-tertiary-fixed": "#001a40",
        "error-container": "#93000a",
        "inverse-on-surface": "#303030",
        "on-secondary": "#2f3131",
        secondary: "#c6c6c7",
        "inverse-primary": "#ff6467",
        "outline-variant": "#603e39",
        "surface-container": "#1f1f1f",
        "surface-container-highest": "#353535",
        "on-secondary-fixed": "#1a1c1c",
        "surface-variant": "#353535",
        "on-primary-fixed-variant": "#7a0000",
        "surface-container-low": "#1b1b1b",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e2e2e2",
        "surface-tint": "#ed0d11",
        error: "#ffb4ab",
        "surface-dim": "#131313",
        "on-tertiary": "#002f67",
        "tertiary-container": "#488fff",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffd7d8",
        "on-primary-container": "#fff7f7",
        "tertiary-fixed-dim": "#acc7ff",
        tertiary: "#acc7ff",
        "on-secondary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#d7e2ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-sm": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "display-lg": [
          "72px",
          { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "900" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.1", fontWeight: "800" },
        ],
        "code-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
